// <auto-generated />
using System;
using CloudFileManager.Infrastructure.DataAccess.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudFileManager.Infrastructure.DataAccess.EfCore.Migrations
{
    [DbContext(typeof(CloudFileDbContext))]
    [Migration("20260215190045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.DirectoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "CreationOrder");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("directories", (string)null);
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Extension");

                    b.HasIndex("FileType");

                    b.HasIndex("RelativePath");

                    b.HasIndex("DirectoryId", "CreationOrder");

                    b.HasIndex("DirectoryId", "Name")
                        .IsUnique();

                    b.ToTable("files", null, t =>
                        {
                            t.HasCheckConstraint("CK_files_extension", "Extension = lower(Extension) AND Extension LIKE '.%'");

                            t.HasCheckConstraint("CK_files_file_type", "FileType IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_files_size_bytes", "SizeBytes >= 0");
                        });
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileMetadataEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Encoding")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId");

                    b.HasIndex("FileId", "FileType")
                        .IsUnique();

                    b.ToTable("file_metadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_file_metadata_type_fields", "((FileType = 1 AND PageCount IS NOT NULL AND Width IS NULL AND Height IS NULL AND Encoding IS NULL) OR (FileType = 2 AND PageCount IS NULL AND Width IS NOT NULL AND Height IS NOT NULL AND Encoding IS NULL) OR (FileType = 3 AND PageCount IS NULL AND Width IS NULL AND Height IS NULL AND Encoding IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.DirectoryEntity", b =>
                {
                    b.HasOne("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.DirectoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileEntity", b =>
                {
                    b.HasOne("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.DirectoryEntity", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directory");
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileMetadataEntity", b =>
                {
                    b.HasOne("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileEntity", "File")
                        .WithOne("Metadata")
                        .HasForeignKey("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileMetadataEntity", "FileId", "FileType")
                        .HasPrincipalKey("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileEntity", "Id", "FileType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.DirectoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("CloudFileManager.Infrastructure.DataAccess.EfCore.Entities.FileEntity", b =>
                {
                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
